/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#f7f9fb",
        "secondary-container": "#afddfe",
        "tertiary-container": "#bbc5ce",
        "surface-container-low": "#f2f4f6",
        "on-primary-fixed-variant": "#2a486e",
        "background": "#f7f9fb",
        "surface-dim": "#d8dadc",
        "surface-tint": "#426087",
        "on-surface-variant": "#42474d",
        "surface-container-high": "#e6e8ea",
        "on-surface": "#191c1e",
        "on-tertiary-container": "#485259",
        "inverse-on-surface": "#eff1f3",
        "on-tertiary": "#ffffff",
        "surface-variant": "#e0e3e5",
        "surface-container-highest": "#e0e3e5",
        "inverse-primary": "#abc8f5",
        "secondary": "#356380",
        "on-error-container": "#93000a",
        "tertiary": "#566067",
        "on-secondary-fixed": "#001e2e",
        "on-background": "#191c1e",
        "primary-fixed": "#d3e3ff",
        "on-tertiary-fixed-variant": "#3e484f",
        "on-tertiary-fixed": "#131d23",
        "outline-variant": "#c2c7ce",
        "on-primary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "outline": "#73777e",
        "surface-container": "#eceef0",
        "inverse-surface": "#2d3133",
        "primary-container": "#a8c5f2",
        "on-error": "#ffffff",
        "on-secondary-fixed-variant": "#194b67",
        "on-primary-container": "#345278",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#bec8d0",
        "primary": "#426087",
        "secondary-fixed-dim": "#9fcced",
        "primary-fixed-dim": "#abc8f5",
        "surface-bright": "#f7f9fb",
        "tertiary-fixed": "#dae4ed",
        "secondary-fixed": "#c7e7ff",
        "on-secondary-container": "#34627e",
        "on-primary-fixed": "#001c39",
        "on-secondary": "#ffffff",
        "error": "#ba1a1a"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Public Sans", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [],
}
